//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_RACKET                      131
#define IDB_ERASER1                     131
#define IDB_BITMAP1                     132
#define IDB_BACKGROUND                  132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_ERASER2                     150
#define IDB_ERASER3                     151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define IDB_TEST                        157
#define IDB_BITMAP3                     160
#define IDB_BLUE                        161
#define IDB_GREEN                       162
#define IDB_BITMAP4                     164
#define IDB_INITSELECTBOX               166
#define IDB_TITLE1                      175
#define IDB_TITLE2                      176
#define IDB_BITMAP5                     177
#define IDB_LONGGRAY                    177
#define IDB_HAND1                       179
#define IDB_BITMAP8                     180
#define IDB_HAND2                       180
#define IDB_BITMAP7                     181
#define IDB_BITMAP9                     182
#define IDB_BITMAP10                    183
#define IDB_BITMAP11                    184
#define IDB_BITMAP12                    185
#define IDB_BITMAP13                    186
#define IDB_BITMAP14                    187
#define IDB_BITMAP15                    188
#define IDB_BITMAP16                    189
#define IDB_BITMAP6                     190
#define IDB_BITMAP28                    205
#define IDB_BITMAP17                    206
#define IDB_BITMAP18                    207
#define IDB_BITMAP19                    208
#define IDB_BITMAP20                    209
#define IDB_BITMAP21                    210
#define IDB_BITMAP22                    211
#define IDB_BITMAP23                    212
#define IDB_BITMAP24                    213
#define IDB_BITMAP25                    214
#define IDB_BITMAP26                    215
#define IDB_BITMAP27                    216
#define IDB_BITMAP29                    219
#define IDB_BG1                         220
#define IDB_BITMAP31                    221
#define IDB_BG2                         221
#define IDB_BITMAP30                    223
#define IDB_BITMAP32                    227
#define IDB_BITMAP33                    228
#define IDB_BITMAP34                    229
#define IDB_BITMAP35                    230
#define IDB_BITMAP36                    231
#define IDB_BITMAP37                    232
#define IDB_BITMAP38                    233
#define IDB_BITMAP39                    234
#define IDB_BITMAP40                    235
#define IDB_BITMAP41                    236
#define IDB_BITMAP42                    237
#define IDB_BITMAP43                    238
#define IDB_BITMAP44                    239
#define IDB_BITMAP45                    240
#define IDB_BITMAP46                    241
#define IDB_BITMAP47                    242
#define IDB_BITMAP48                    243
#define IDB_BITMAP49                    244
#define IDB_BITMAP50                    245
#define IDB_BITMAP51                    248
#define IDB_BITMAP52                    249
#define IDB_BITMAP53                    250
#define IDB_BITMAP54                    251
#define IDB_BITMAP55                    252
#define IDB_BITMAP56                    253
#define IDB_BITMAP57                    254
#define IDB_BITMAP58                    255
#define IDB_BITMAP59                    256
#define IDB_BITMAP60                    257
#define IDB_BITMAP61                    258
#define IDB_BITMAP62                    259
#define IDB_BITMAP63                    260
#define IDB_BITMAP64                    261
#define IDB_BITMAP65                    262
#define IDB_BITMAP66                    263
#define IDB_BITMAP67                    264
#define IDB_BITMAP68                    265
#define IDB_BITMAP69                    266
#define IDB_BITMAP70                    267
#define IDB_BITMAP71                    268
#define IDB_BITMAP72                    269
#define IDB_BITMAP73                    270
#define IDB_BITMAP74                    271
#define IDB_BITMAP75                    272
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        273
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
